Repository UMC-BRUSHWORK/backend, pull requests merged in 2024-01, with the labels that each got.

#19 issue/5 ✨ [Feat] 해당 API에 대한 Swagger 추가
  index.js
  package.json
  src/routes/health.route.js
  swagger-output.json
Labels: :sparkles: feature

#20 issue/5 💚 [Ci] dev_deploy 수정
  .github/workflows/dev_deploy.yml
Labels: :construction_worker: ci

#21 :green_heart: [Ci] 빌드 오류난거 수정
  package-lock.json
  package.json
  yarn.lock
Labels: :construction_worker: ci

#22 issue/5 ➕ [Add] 배포 시 module 오류로 추가 모듈 다운
  package-lock.json
  package.json
Labels: :construction_worker: ci

#25 issue/24 🔧 [Update] Swagger 구조 변경 (CD 적용 목적)
  config/swagger.config.js
  index.js
  package-lock.json
  package.json
  swagger-output.json
  swagger.js
  swagger/test.swagger.yaml
  swagger/user.swagger.yaml
  yarn.lock
Labels: :construction_worker: ci

#26 💚 [Ci] Procfile 수정
  Procfile
Labels: :construction_worker: ci

#39 issue/15 ✨ [Feat] API 구조 수정
  src/controllers/user.controller.js
  src/services/user.service.js
  src/swagger/user.swagger.yaml
Labels: :sparkles: feature

#37 ✨ [FEAT]로그아웃 API
  config/response.status.js
  index.js
  package-lock.json
  package.json
  src/controllers/auth.controller.js
  src/dtos/auth.dto.js
  src/middleware/auth.js
  src/middleware/jwt.js
  src/models/auth.dao.js
  src/models/auth.sql.js
  src/routes/auth.route.js
  src/routes/test.route.js
  src/services/auth.service.js
  src/swagger/auth.swagger.yaml
  swagger.json
  yarn.lock
Labels: :sparkles: feature

#53 🔀 [Merge] 이슈 브랜치 병합
  config/response.status.js
  config/swagger.config.js
  index.js
  src/controllers/auth.controller.js
  src/controllers/product.controller.js
  src/dtos/auth.dto.js
  src/dtos/product.dto.js
  src/middleware/auth.js
  src/middleware/jwt.auth.js
  src/models/auth.dao.js
  src/models/auth.sql.js
  src/models/product.dao.js
  src/models/product.sql.js
  src/models/user.sql.js
  src/providers/product.provider.js
  src/routes/auth.route.js
  src/routes/product.route.js
  src/services/auth.service.js
  src/services/product.service.js
  src/swagger/auth.swagger.yaml
  src/swagger/product.swagger.yaml
  src/swagger/review.swagger.js
  swagger.json
  yarn.lock
Labels: :sparkles: feature

#57 🚚 [Rename] 변수명 수정
  src/controllers/auth.controller.js
  src/controllers/product.controller.js
  src/services/auth.service.js
Labels: :recycle: refactor

#58 🐛 [Fix] 회원 가입 API 오류 수정
  src/controllers/auth.controller.js
  src/models/auth.dao.js
  src/models/auth.sql.js
  src/services/auth.service.js
  src/swagger/auth.swagger.yaml
Labels: :recycle: refactor
